---
:global:
  library_type:
    module-sync-testing-target:        [nservicebus-custom-check]

README.md:
  description: 'My module has an awesome description'
  my_array:
    - item1
    - item2

README2.md:
  description: 'first time sync only'